### ISSUE TITLE
Task List !

### ISSUE THREAD

**Issue by code-monk08** [code-monk08/Dirtiest-Tweeters#1]
- [ ] make a list of say n users whose tweets could be scraped using live stream of tweets and profane word list.

- [ ] obtain say up to 1000 tweets for each user from user's list.

- [ ] profanity checker function will check each of the tweets for every user and based on that it will assign some score to every user.

- [ ] that assigned score along with username of the user will be appended to some other file or maybe a database and will  be first sorted according to number of followers and then according to the number of obscene tweets.
